[
    {  
        "name": "Walk through the Santorini Vineyards" ,
        "userImg": "https://i.imgur.com/XRZku3j.jpg" ,
        "userName": "Liam Wilson",
        "activities": "Here would be the activities available",
        "duration": 2 ,
        "city": "Santorini ",
        "country": "Grecia" ,
        "likes":["SantoriniWineTour", "GreekWineTasting"],
        "price": 4 ,
        "hashtags": ["SantoriniWineTour", "GreekWineTasting"],
        "comments": ["SantoriniWineTour", "GreekWineTasting"]
    },
    {
        "name": "Art and Culture in Berlin" ,
        "userImg": "https://i.imgur.com/Nrz2dM0.jpg" ,
        "userName": "Sophia Johnson ",
        "activities": "Here would be the activities available",
        "duration": 4 ,
        "city": "Berlín",
        "country": "Alemania" ,
        "likes":["BerlinArtScene"],
        "price": 2 ,
        "hashtags": ["BerlinArtScene"],
        "comments": ["BerlinArtScene"]
    },
    {
        "name": "Buenos Aires Night" ,
        "userImg": "https://i.imgur.com/x1VPmjm.jpg" ,
        "userName": "Mia Andersen",
        "activities": "Here would be the activities available",
        "duration": 6 ,
        "city": "Buenos Aires",
        "country": "Argentina" ,
        "likes":["NightOutInArgentina", "BuenosAiresNightlife"],
        "price": 5 ,
        "hashtags": ["NightOutInArgentina", "BuenosAiresNightlife"],
        "comments": ["NightOutInArgentina", "BuenosAiresNightlife"]
    },
    {
        "name": "Diving trip in the Maldives" ,
        "userImg": "https://i.imgur.com/nXQSdg0.jpg" ,
        "userName": "Isabella Silva ",
        "activities": "Here would be the activities available",
        "duration": 0 ,
        "city": "Malé",
        "country": "Maldivas" ,
        "likes":["UnderwaterAdventure", "MarineLifeExploration"],
        "price": 4 ,
        "hashtags": ["UnderwaterAdventure", "MarineLifeExploration"],
        "comments": ["UnderwaterAdventure", "MarineLifeExploration"]
    },
    {
        "name": "New York on Foot and by Bike" ,
        "userImg": "https://i.imgur.com/joeIGRo.jpg" ,
        "userName": "Fabio Rossi ",
        "activities": "Here would be the activities available",
        "duration": 5 ,
        "city": "New York",
        "country": "EE UU" ,
        "likes":["NYCExploration", "CitySightseeing", "WalkingAndBiking"],
        "price": 1 ,
        "hashtags": ["NYCExploration", "CitySightseeing", "WalkingAndBiking"],
        "comments": ["NYCExploration", "CitySightseeing", "WalkingAndBiking"]
    },
    {
        "name": "Canadian Nature: Mountains and Lakes" ,
        "userImg": "https://i.imgur.com/QLZLIqs.jpg" ,
        "userName": "Alexander Smith",
        "activities": "Here would be the activities available",
        "duration": 6 ,
        "city": "Toronto",
        "country": "Canada" ,
        "likes":["CanadianAdventure"],
        "price": 1 ,
        "hashtags": ["CanadianAdventure"],
        "comments": ["CanadianAdventure"]
    },
    {
        "name": "Adventure in the Pyramids and the Desert of Egypt" ,
        "userImg": "https://i.imgur.com/cAXr79c.jpg" ,
        "userName": "Elena Petrov",
        "activities": "Here would be the activities available",
        "duration": 3 ,
        "city": "El Cairo",
        "country": "Egipto" ,
        "likes":["EgyptianAdventure", "PyramidsExploration"],
        "price": 1 ,
        "hashtags": ["EgyptianAdventure", "PyramidsExploration"],
        "comments": ["EgyptianAdventure", "PyramidsExploration"]
    },
    {
        "name": "Romantic venice" ,
        "userImg": "https://i.imgur.com/16g7PA8.jpg" ,
        "userName": "Sofia Martinez ",
        "activities": "Here would be the activities available",
        "duration": 2 ,
        "city": "Venecia",
        "country": "Italia" ,
        "likes":["johndoe123", "traveler23", "adventuregirl"],
        "price": 1 ,
        "hashtags": ["johndoe123", "traveler23", "adventuregirl"],
        "comments": ["johndoe123", "traveler23", "adventuregirl"]
    },
    {
        "name": "Gastronomic Adventure in Buenos Aires" ,
        "userImg": "https://i.imgur.com/9HYLQlX.jpg" ,
        "userName": "Pablo García",
        "activities": "Here would be the activities available",
        "duration": 3 ,
        "city": "Buenos Aires",
        "country": "Argentina" ,
        "likes":["BuenosAiresFoodie" , "ArgentinianCuisine", "FoodAndWineTour"],
        "price": 5 ,
        "hashtags": ["BuenosAiresFoodie" , "ArgentinianCuisine", "FoodAndWineTour"],
        "comments": ["BuenosAiresFoodie" , "ArgentinianCuisine", "FoodAndWineTour"]
    },
    {
        "name": "Santorini at Sunset" ,
        "userImg": "https://i.imgur.com/oQ64tzK.jpg" ,
        "userName": "Emma Nguyen ",
        "activities": "Here would be the activities available",
        "duration": 1 ,
        "city": "Santorini",
        "country": "Grecia" ,
        "likes":["SantoriniSunset",  "IslandParadise"],
        "price": 0 ,
        "hashtags": ["SantoriniSunset",  "IslandParadise"],
        "comments": ["SantoriniSunset",  "IslandParadise"]
    }
]